### PR TITLE
Phase 1

### PR DESCRIPTION
**Pull request by Ni-Ma**
Phase 1 branch contains all of the code for the functionality of the GUI.  The layout, color coding, and the key are included in the GUI.  In addition the nucleus will generate for all elements and you can zoom and pan on the model now.

### CODE REVIEW

**Comment by Ni-Ma** [comment]
Did you pull the code from the phase 1 branch?  This was the case with the master branch because the implementation of all buttons hadn't been added yet, but I've just run the program with the phase 1 branch again using 5 random buttons and they all display the correct element.

**Comment by jgeddes101** [comment]
I thought it was from phase 1 but I guess I was wrong, I'll try to pull it
again.

**Comment by filerJ94** [comment]
With the first draft it happens.  With the new phase 1 code, it displays different elements in the model view.

**Comment by Ni-Ma** [comment]
I think a lot of the confusion is the fact that I uploaded a zip in the master branch, but in the phase-1 branch I uploaded specific class files.  I tried to remove that folder but can't find a way to do it.  My plan is to continue uploading just the class files, so those will be the most up to date.

**Pull request merged**
