### PR TITLE
Update of addButton method and addition of Type

### PR DESCRIPTION
**Pull request by jgeddes101**
I've updated the addButton method to read in the element button information from a file so that we don't have to hard code everything in the program. I've also added a Type enum for the classification of each metal. In case you're not super familiar with reading files in java, the elementList.txt file must be placed in the main project folder for execution, not the package folder. I'm working on adjusting the element information in a similar way as well, but let me know what you think of these changes.

### CODE REVIEW

**Comment by Ni-Ma** [comment]
The master branch already includes an implementation of the addButton and an addKey method.  These were implemented a few days ago as pointed out by jfiler in a previous comment.  I see that this cuts down on some code, but I'm not sure what we gain from this implementation vs what is already coded.  This seems to just move what is hard coded to an external .txt file.  I'm not seeing the benefit of doing this.

**Comment by jgeddes101** [comment]
This is just the first stage of what I'm working on and I realize that it
might not be clear at this stage why I went with the text file route. I'll
finish the rest of it and upload it to give you a better idea of the
reasoning.

**Comment by Ni-Ma** [comment]
I had already added the functionality for adding element density to the information window and providing appropriate formatting.  I will wait to post that to see what you are working on.  You may want to make sure that the time you are spending results in code compatible with the master branch since jfiler could not compile what you currently have.  I will not make any more changes until you have uploaded what you are working on since it doesn't seem like it will be compatible with any functionality that I am working on.  As a reminder, we have until the end of the week to finalize the feature set so the test plan can be submitted that will test all features on Sunday.

**Comment by jgeddes101** [comment]
TableGui.Java, Type.Java, and elementList.txt have all been updated. I've been testing them with Nick's most recent uploaded files and the application has been working fine.

**Comment by Ni-Ma** [comment]
I have been unable to get this code to work.  After some work, I've been able to get it to compile, but the table comes up blank.

**Comment by Ni-Ma** [comment]
OK, after some more work, I have been able to get this to work.  Since we have adjusted it to create the element object on demand, I'm ok with it.  I think it is much more complex than is necessary but I'm willing to adopt this implementation.  I have made a minor change to the TableGui class to remove the setPrefWidth line in the add button since it is not used due to the setPrefSize line.  I also added a throws IOException to the start method in the PeriodicTable class since NetBeans did not want to run it without that.

**Pull request merged**
